
package Formularios;

import Conexiones.Cliente;
import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 * Clase que representa una carta especial, es decir, adicionalmente posee un nombre y una acción.
 * @author Stalin
 */
public class CartaEspecial extends Carta {
    
    private String nombre;
    
    
    
    /**
     * 
     * @param nombre
     * @param color
     * @param valor 
     */
    public CartaEspecial(String nombre,String color,int valor) {
        super(valor, color);
        this.nombre = nombre;
        initComponents();
        this.setSize(134, 205); //se selecciona el tamaño del panel
    }
    
    /**
     * 
     * @param nombre
     * @param color
     * @param valor
     * @param poseedor
     * @param ubicacion 
     */
    public CartaEspecial(String nombre,String color,int valor, Cliente poseedor, Tablero ubicacion) {
        super(valor, color, poseedor,ubicacion);
        this.nombre = nombre;
        initComponents();
        this.setSize(134, 205); //se selecciona el tamaño del panel
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 97, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        //JOptionPane.showMessageDialog(this, this.nombre+" "+this.color+": me pulsaron");
        if(nombre.equalsIgnoreCase("+4") || nombre.equalsIgnoreCase("CC")){
            cambiarColor();
        }
        ubicacion.removeDeMisCartas(nombre, color);
        poseedor.enviar("add,carta,"+poseedor.getMiIp()+",CartaEspecial,"+nombre+","+color+","+valor);
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    public void paint(Graphics grafico) {
    
    Dimension height = getSize();

    //Se selecciona la imagen que tenemos en el paquete de la //ruta del programa

    ImageIcon Img = new ImageIcon(getClass().getResource("/Imagenes/"+nombre+color+".jpg")); 

    //se dibuja la imagen que tenemos en el paquete Images //dentro de un panel

    grafico.drawImage(Img.getImage(), 0, 0, 132, 204, null);

    setOpaque(false);
    super.paintComponent(grafico);
    }

    /**
     * @return the nombre
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * @param nombre the nombre to set
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    /**
     * 
     */
    public void cambiarColor(){
        String colores[] = new String[] {"Amarillo","Azul","Rojo","Verde"};
        int intColor = JOptionPane.showOptionDialog(null, "Selecciona el nuevo color", "Cambio de color",JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE,new ImageIcon(getClass().getResource("/Imagenes/"+nombre+color+".jpg")), colores, colores[0]);
        
        switch(intColor){
            
            case 0:{
                color = "Amarillo";
            }break;
            
            case 1:{
                color = "Azul";
            }break;
            
            case 2:{
                color = "Rojo";
            }break;
            
            case 3:{
                color = "Verde";
            }break;
                
            default:{
                cambiarColor();
            }break;
        }
    }

}
