/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Conexiones.Cliente;
import Esencial.Sonido;
import Esencial.Usuario;

/**
 * Clase que representa una ventana a través de la cual un anfitrión puede configurar el juego.
 * @author Stalin
 */
public class Creacion extends javax.swing.JFrame {
    
    Fondo  imagenFondo;
    public static Usuario usuarioActual;
    public static String hostname="";
    private final Sonido musicaFondo;
    

    /**
     * Creates new form MenuJuego
     */
    public Creacion() {
        imagenFondo = new Fondo("/Imagenes/fondoCreacion.jpg");
        
        
        
        initComponents();
        miIp.setText("Mi IP: "+Cliente.saberMiIp());
        miIp.setEditable(false);
        
        this.setSize(imagenFondo.getWidth()+15,imagenFondo.getHeight());
        
        fondo.add(imagenFondo);
        fondo.setOpaque(false);

        this.setLocationRelativeTo(null);
        
        musicaFondo = new Sonido(this);
        musicaFondo.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        tipoJuego = new javax.swing.JLabel();
        cantidadJugadores = new javax.swing.JLabel();
        cboPuntos = new javax.swing.JComboBox();
        cboTipoJuego = new javax.swing.JComboBox();
        cancelar = new javax.swing.JButton();
        empezar = new javax.swing.JButton();
        puntos = new javax.swing.JLabel();
        cboCantidadJugadores = new javax.swing.JComboBox();
        miIp = new javax.swing.JTextField();
        mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(0, 153, 0));

        tipoJuego.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        tipoJuego.setText("Tipo de Juego");

        cantidadJugadores.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        cantidadJugadores.setText("Cantidad de Jugadores");

        cboPuntos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "100", "200", "300", "400", "500" }));

        cboTipoJuego.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rapido", "Acumulativo" }));

        cancelar.setText("Cancelar");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });

        empezar.setText("Empezar");
        empezar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                empezarMouseClicked(evt);
            }
        });

        puntos.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        puntos.setText("Puntos");

        cboCantidadJugadores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4" }));

        miIp.setText("Mi IP: XXX.XXX.XXX.XXX");

        mensaje.setText("Si estás conectado a un router debes consultar tu ip en www.cualesmiip.com");

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(tipoJuego)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboTipoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(miIp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(empezar)
                                .addGap(18, 18, 18)
                                .addComponent(cancelar)))
                        .addContainerGap(179, Short.MAX_VALUE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(cantidadJugadores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCantidadJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(puntos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(mensaje)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadJugadores)
                    .addComponent(cboCantidadJugadores, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(puntos)
                    .addComponent(cboPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoJuego)
                    .addComponent(cboTipoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(miIp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empezar)
                    .addComponent(cancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mensaje)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empezarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_empezarMouseClicked
       
        musicaFondo.Stop();
        String[] args = null;
       
       int cantidadJugadores = Integer.parseInt(cboCantidadJugadores.getSelectedItem().toString());
       String modalidad = cboTipoJuego.getSelectedItem().toString();
       int puntos = Integer.parseInt(cboPuntos.getSelectedItem().toString());
       
       if(modalidad.equalsIgnoreCase("Rapido"))
           puntos=0;
       
       Tablero.hostname = this.hostname;
       Tablero.usuarioActual = this.usuarioActual;
       Tablero.main(args, this.usuarioActual, cantidadJugadores, modalidad, puntos);
       this.dispose();
    }//GEN-LAST:event_empezarMouseClicked

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        musicaFondo.Stop();
        String[] args=null;
        Sala.hostname = this.hostname;
        Sala.usuarioActual = this.usuarioActual;
        Sala.main(args);
        this.dispose();
    }//GEN-LAST:event_cancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Creacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Creacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel cantidadJugadores;
    private javax.swing.JComboBox cboCantidadJugadores;
    private javax.swing.JComboBox cboPuntos;
    private javax.swing.JComboBox cboTipoJuego;
    private javax.swing.JButton empezar;
    private javax.swing.JPanel fondo;
    private javax.swing.JLabel mensaje;
    private javax.swing.JTextField miIp;
    private javax.swing.JLabel puntos;
    private javax.swing.JLabel tipoJuego;
    // End of variables declaration//GEN-END:variables

    
}
