/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Esencial.Imagen;
import Esencial.Usuario;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FichaUsuario extends javax.swing.JPanel {
    Usuario usuario;
    int rank;

    /**
     * Creates new form FichaUsuario
     */
    public FichaUsuario(Usuario usuario,int rank) {
        this.usuario = usuario;
        this.rank = rank;
        
        initComponents();
        
        llenarFicha();
    }
    
    
    public void llenarFicha(){
        lblNickname.setText(usuario.getNickname());
        lblpartidasJugadas.setText(lblpartidasJugadas.getText()  +" "+ usuario.getPartidasJugadas());
        lblPartidasGanadas.setText(lblPartidasGanadas.getText()  +" "+ usuario.getPartidasGanadas());
        lblPartidasPerdidas.setText(lblPartidasPerdidas.getText()+" "+ usuario.getPartidasPerdidas());
        lblPartidasAbandonadas.setText(lblPartidasAbandonadas.getText()+" "+ usuario.getPartidasAbandonadas() );
        lblRank.setText(lblRank.getText()+" "+rank);
        panelImagen.add(new Fondo(150,150,new ImageIcon(Imagen.decodeToImage(usuario.getImagen()))));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImagen = new javax.swing.JPanel();
        lblNickname = new javax.swing.JLabel();
        lblpartidasJugadas = new javax.swing.JLabel();
        lblPartidasGanadas = new javax.swing.JLabel();
        lblPartidasPerdidas = new javax.swing.JLabel();
        lblPartidasAbandonadas = new javax.swing.JLabel();
        lblRank = new javax.swing.JLabel();

        setBorder(new javax.swing.border.MatteBorder(null));

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        lblNickname.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        lblNickname.setText("Nickname");

        lblpartidasJugadas.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        lblpartidasJugadas.setText("Jugadas:");

        lblPartidasGanadas.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        lblPartidasGanadas.setText("Ganadas:");

        lblPartidasPerdidas.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        lblPartidasPerdidas.setText("Perdidas:");

        lblPartidasAbandonadas.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        lblPartidasAbandonadas.setText("Dejadas:");

        lblRank.setFont(new java.awt.Font("Kristen ITC", 1, 16)); // NOI18N
        lblRank.setText("Rank:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblRank)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPartidasAbandonadas)
                    .addComponent(lblNickname)
                    .addComponent(lblPartidasPerdidas)
                    .addComponent(lblPartidasGanadas)
                    .addComponent(lblpartidasJugadas))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNickname)
                        .addGap(21, 21, 21)
                        .addComponent(lblpartidasJugadas)
                        .addGap(21, 21, 21)
                        .addComponent(lblPartidasGanadas)
                        .addGap(21, 21, 21)
                        .addComponent(lblPartidasPerdidas)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPartidasAbandonadas)
                    .addComponent(lblRank))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNickname;
    private javax.swing.JLabel lblPartidasAbandonadas;
    private javax.swing.JLabel lblPartidasGanadas;
    private javax.swing.JLabel lblPartidasPerdidas;
    private javax.swing.JLabel lblRank;
    private javax.swing.JLabel lblpartidasJugadas;
    private javax.swing.JPanel panelImagen;
    // End of variables declaration//GEN-END:variables
}
