/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Esencial.Imagen;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class ImagenFondo extends javax.swing.JPanel {
    String strImagen;
    Image imagen;
    ImageIcon imagenIcono;
    JPanel panelImagen;
    
    /**
     * Creates new form ImagenFondo
     */
    public ImagenFondo(String strImagen, JPanel panelImagen, JPanel fondo) {
        initComponents();
        this.strImagen = strImagen;
        this.panelImagen = panelImagen;
        
        imagenIcono = new ImageIcon(Imagen.decodeToImage(strImagen));
        
        imagen = imagenIcono.getImage();
        
        this.setBackground(fondo.getBackground());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    
    
    @Override
    public void paintComponent(Graphics grafico){
     
        if(imagen!=null){
            grafico.drawImage(imagen,125 ,0 , panelImagen.getWidth(), panelImagen.getHeight(), null);
        }
    
    }
    
}
