
package Formularios;

import Esencial.ListaJugadores;
import Esencial.ListaCartas;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 * Clase que representa la pila de robo, es decir, de esta pila los jugadores tomarán cartas cuando sea necesario.
 * @author Stalin
 */
public class PilaRobo extends javax.swing.JPanel {
    
    private ListaCartas listaCartas;

    /**
     * 
     */
    public PilaRobo() {
        initComponents();
        listaCartas = new ListaCartas();
        cargarCartas();
        Barajar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    public void Barajar(){
        int a,b;
        Random aleatorio = new Random();
        for(int i=0;((i<10000) &&(listaCartas.size()>0));i++){
            
            a = aleatorio.nextInt(listaCartas.size()-1);
            b = aleatorio.nextInt(listaCartas.size()-1);
            
            listaCartas.intercambia(a, b);
            
        }
        
    }
    
    public void quitarUltima(){
        try {
            listaCartas.remove(listaCartas.size()-1);
        } catch (Exception e) {
        }
    }
    
    public void cargarCartas(){
        String[] color = {"Amarillo","Azul","Verde","Rojo"};
        
        String[] nombre = {"+2","R","S","CC","+4"};
        
        for(int i =3; i<nombre.length;i++){
            CartaEspecial cartaEspecial = new CartaEspecial(nombre[i],"Negro",50);
            for(int k=0;k<4;k++)
                    listaCartas.add(cartaEspecial);
        }
        
        for(int i=0;i<nombre.length-2;i++)
            for(int j=0;j<color.length;j++){
                CartaEspecial cartaEspecial = new CartaEspecial(nombre[i],color[j],20);
                
                for(int k=0;k<2;k++)
                    listaCartas.add(cartaEspecial);
                
            }
        
        for(int i=0;i<10;i++)
            for(int j =0; j<color.length;j++){
                CartaNormal cartaNormal = new CartaNormal(i,color[j]);
                if(i!=0){
                    listaCartas.add(cartaNormal);
                }
                listaCartas.add(cartaNormal);
            }
            
    }

    /**
     * @return the listaCartas
     */
    public ListaCartas getListaCartas() {
        return listaCartas;
    }

    /**
     * @param listaCartas the listaCartas to set
     */
    public void setListaCartas(ListaCartas listaCartas) {
        this.listaCartas = listaCartas;
    }
  
}
