/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import Esencial.Sonido;
import Esencial.Usuario;
import Esencial.XML;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Clase que permite gestionar y visualizar las posiciones de los mejores jugadores, tomando como criterio de ordenamiento las partidas ganadas.
 * @author Stalin
 */
public class Ranking extends javax.swing.JFrame {
    private Fondo imagenFondo;
    private Sonido musicaFondo;
    private List listaDeUsuarios;
    public static String hostname="";
    public static Usuario usuarioActual;
    private JPanel panelDeFichas;

    /**
     * Creates new form Ranking
     */
    public Ranking() {
        imagenFondo = new Fondo("/Imagenes/fondoRanking.jpg");
        
        panelDeFichas = new JPanel(new GridLayout(1, 3, 17, 0));
        panelDeFichas.setSize(20, 219);
        
        
        initComponents();
        
        this.setSize(imagenFondo.getWidth(),imagenFondo.getHeight());
        //this.setResizable(false);
        fondo.add(imagenFondo);
        fondo.setOpaque(false);
        this.setLocationRelativeTo(null);

        musicaFondo = new Sonido(this);
        musicaFondo.play();
        
        
        this.setVisible(true);
        JOptionPane.showMessageDialog(this, "Se van descargar los\ndatos actualizados\nde la base de datos y\n"
                                          + "tardará unos segundos\nPulse aceptar para\ncomenzar la descarga.","Cargando Ranking",1,new ImageIcon(getClass().getResource("/Imagenes/cargando.gif")));
        cargarListaDeUsuarios();
        agregarFichas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        scrpListaDeFichas = new javax.swing.JScrollPane();
        Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Volver.setText("Volver");
        Volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VolverMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrpListaDeFichas, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(Volver)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(Volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrpListaDeFichas, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VolverMouseClicked
        musicaFondo.Stop();
        String[] args=null;
        Sala.hostname = this.hostname;
        Sala.usuarioActual = this.usuarioActual;
        Sala.main(args);
        this.dispose();
    }//GEN-LAST:event_VolverMouseClicked

    
    
    public void agregarFichas(){
        FichaUsuario ficha;
        for(int i=0;i<listaDeUsuarios.size();i++){
            ficha = new FichaUsuario(((Usuario) listaDeUsuarios.get(i)),i+1);
            
            
            panelDeFichas.add(ficha);
            panelDeFichas.setVisible(true);
            ficha.setVisible(true);
            scrpListaDeFichas.setVisible(true);
            this.setVisible(true);
            this.repaint();
            scrpListaDeFichas.setViewportView(panelDeFichas);
            
            
        }
        
    }
    
    public void cargarListaDeUsuarios(){
        XML xml = new XML(this.hostname);
        xml.cargarUsuarios();
        xml.EcribirDocumento();
        
        this.listaDeUsuarios = xml.obtenerListaDeUsuarios();
        
        
        Collections.sort(listaDeUsuarios, new Comparator<Usuario>(){
            @Override
            public int compare(Usuario u1, Usuario u2) {
                return new Integer(u2.getPartidasGanadas()).compareTo(new Integer(u1.getPartidasGanadas()));
            }
	});
    }
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ranking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ranking();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Volver;
    private javax.swing.JPanel fondo;
    private javax.swing.JScrollPane scrpListaDeFichas;
    // End of variables declaration//GEN-END:variables
}
